name: Deploy Terraform

on:
  push:
    branches: [main]

jobs:
  apply-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Authenticate GCP
        run: |
            echo '${{ secrets.MY_SERVICE_ACCOUNT_CREDENTIALS }}' > key.json
            echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json" >> $GITHUB_ENV

      - name: Set Terraform Variables
        run: echo "TF_VAR_project_id=${{ secrets.MY_GCP_PROJECT }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: envs/dev

      - name: Terraform Apply (Dev)
        run: terraform apply -auto-approve -var-file=dev.tfvars
        working-directory: envs/dev

  apply-prod:
    needs: apply-dev
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Authenticate GCP
        run: |
          echo "${{ secrets.MY_SERVICE_ACCOUNT_CREDENTIALS }}" > key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json" >> $GITHUB_ENV

      - name: Set Terraform Variables
        run: echo "TF_VAR_project_id=${{ secrets.MY_GCP_PROJECT }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        working-directory: envs/prod

      - name: Terraform Apply (Prod)
        run: terraform apply -auto-approve -var-file=prod.tfvars
        working-directory: envs/prod