name: PR Terraform Plan

on:
  pull_request:
    branches: [main]

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, prod]

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Authenticate GCP
        run: |
          echo '${{ secrets.MY_SERVICE_ACCOUNT_CREDENTIALS }}' > key.json
        

      - name: Terraform Init
        run: terraform init
        working-directory: envs/${{ matrix.env }}

      - name: Terraform Plan
        run: terraform plan \
             -var="project_id=${{ secrets.MY_GCP_PROJECT }}" \
             -var-file=${{ matrix.env }}.tfvars
        working-directory: envs/${{ matrix.env }}