name: PR Terraform Plan

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    name: Terraform Plan (Dev & Prod)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [dev, prod]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate GCP
        run: |
            echo '${{ secrets.MY_SERVICE_ACCOUNT_CREDENTIALS }}' > key.json
            echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: envs/${{ matrix.env }}
        run: terraform init

      - name: Terraform Plan
        working-directory: envs/${{ matrix.env }}
        run: |
          terraform plan \
            -var="project_id=${{ secrets.MY_GCP_PROJECT }}" \
            -var-file=${{ matrix.env }}.tfvars